model BasicBuilder -ndm 2 -ndf 3  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
set storyheight 3960.0;    
set baywidth 9150.0;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
set E 206000;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
set Fy 248;
set Arigid 1.0E+6;
set b 0.03;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
set matTag 1;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
uniaxialMaterial Steel01 $matTag $Fy $E $b;
set matTagRigid 11;
uniaxialMaterial Elastic $matTagRigid [expr 1.0E+10];                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
# nodes    
for {set ifloor 1}  {$ifloor < 5} {incr ifloor} {
    for {set icol 1}  {$icol < 7} {incr icol} {
        set x [expr ($icol-1)*$baywidth];
        set y [expr ($ifloor-1)*$storyheight];
        node [expr $ifloor*10+$icol] $x $y;  
    }
}        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
for {set icol 1}  {$icol < 7} {incr icol} {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
    fix [expr 1*10+$icol] 1 1 1; 
}

fix 46 0 0 1;      
fix 36 0 0 1; 
fix 26 0 0 1;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

source WSection.tcl;

# section
set secTag_W14x257 1;
WSection $secTag_W14x257 $matTag 416.6 406.4 48 30 10 2 10 2;  
set secTag_W14x311 2;
WSection $secTag_W14x311 $matTag 434.3 411.5 57.4 35.8 10 2 10 2;  
set secTag_W14x68 3;
WSection $secTag_W14x68 $matTag 355.6 254.0 18.3 10.5 10 2 10 2;
set secTag_W33x118 4;
WSection $secTag_W33x118 $matTag 835.7 292.1 18.8 14.0 10 2 10 2;
set secTag_W30x116 5;
WSection $secTag_W30x116 $matTag 762.0 266.7 21.6 14.4 10 2 10 2;
set secTag_W24x68 6;
WSection $secTag_W24x68 $matTag 602.0 227.8 14.9 10.5 10 2 10 2;
set secTag_W21x44 7;
WSection $secTag_W21x44 $matTag 525.8 165.1 11.4 8.9 10 2 10 2;

set transfTag 1;
geomTransf Corotational $transfTag;
source SegmentedElement.tcl;

# colomn 
set N_segment 3; 
# 1
SegmentedElement 11101 $N_segment 112101 11 21 10 $secTag_W14x257 $transfTag; 
SegmentedElement 12101 $N_segment 213101 21 31 10 $secTag_W14x257 $transfTag;
SegmentedElement 13101 $N_segment 314101 31 41 10 $secTag_W14x257 $transfTag; 
# 2
SegmentedElement 11201 $N_segment 122201 12 22 10 $secTag_W14x311 $transfTag; 
SegmentedElement 12201 $N_segment 223201 22 32 10 $secTag_W14x311 $transfTag;
SegmentedElement 13201 $N_segment 324201 32 42 10 $secTag_W14x311 $transfTag; 
# 3
SegmentedElement 11301 $N_segment 132301 13 23 10 $secTag_W14x311 $transfTag; 
SegmentedElement 12301 $N_segment 233301 23 33 10 $secTag_W14x311 $transfTag;
SegmentedElement 13301 $N_segment 334301 33 43 10 $secTag_W14x311 $transfTag; 
# 4
SegmentedElement 11401 $N_segment 142401 14 24 10 $secTag_W14x257 $transfTag; 
SegmentedElement 12401 $N_segment 243401 24 34 10 $secTag_W14x257 $transfTag;
SegmentedElement 13401 $N_segment 344401 34 44 10 $secTag_W14x257 $transfTag;
# 5
SegmentedElement 11501 $N_segment 152501 15 25 10 $secTag_W14x68 $transfTag; 
SegmentedElement 12501 $N_segment 253501 25 35 10 $secTag_W14x68 $transfTag;
SegmentedElement 13501 $N_segment 354501 35 45 10 $secTag_W14x68 $transfTag;
# 6
element corotTruss 116 16 26 $Arigid $matTagRigid -doRayleigh 1; 
element corotTruss 126 26 36 $Arigid $matTagRigid -doRayleigh 1;
element corotTruss 136 36 46 $Arigid $matTagRigid -doRayleigh 1;

# beam 
set N_segment 1; 
# 1 bay
SegmentedElement 22101 $N_segment 212201 21 22 10 $secTag_W33x118 $transfTag; 
SegmentedElement 23101 $N_segment 313201 31 32 10 $secTag_W30x116 $transfTag;
SegmentedElement 24101 $N_segment 414201 41 42 10 $secTag_W24x68 $transfTag; 
# 2 bay
SegmentedElement 22201 $N_segment 222301 22 23 10 $secTag_W33x118 $transfTag; 
SegmentedElement 23201 $N_segment 323301 32 33 10 $secTag_W30x116 $transfTag;
SegmentedElement 24201 $N_segment 424301 42 43 10 $secTag_W24x68 $transfTag; 
# 3 bay
SegmentedElement 22301 $N_segment 232401 23 24 10 $secTag_W33x118 $transfTag; 
SegmentedElement 23301 $N_segment 333401 33 34 10 $secTag_W30x116 $transfTag;
SegmentedElement 24301 $N_segment 434401 43 44 10 $secTag_W24x68 $transfTag; 
# 4 bay
node 241 [expr 3*$baywidth] [expr 1*$storyheight];  
node 341 [expr 3*$baywidth] [expr 2*$storyheight];  
node 441 [expr 3*$baywidth] [expr 3*$storyheight];  
node 251 [expr 4*$baywidth] [expr 1*$storyheight];  
node 351 [expr 4*$baywidth] [expr 2*$storyheight];  
node 451 [expr 4*$baywidth] [expr 3*$storyheight];
equalDOF 24 241 1 2;
equalDOF 34 341 1 2;
equalDOF 44 441 1 2;
equalDOF 25 251 1 2;
equalDOF 35 351 1 2;
equalDOF 45 451 1 2;
SegmentedElement 22401 $N_segment 24125101 241 251 10 $secTag_W21x44 $transfTag; 
SegmentedElement 23401 $N_segment 34135101 341 351 10 $secTag_W21x44 $transfTag;
SegmentedElement 24401 $N_segment 44145101 441 451 10 $secTag_W21x44 $transfTag;
# 5 bay
element corotTruss 225 25 26 $Arigid $matTagRigid -doRayleigh 1; 
element corotTruss 235 35 36 $Arigid $matTagRigid -doRayleigh 1; 
element corotTruss 245 45 46 $Arigid $matTagRigid -doRayleigh 1; 

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
# loading                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
initialize                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
source procedure010.tcl                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
set modelName "NXFmodel" ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
